# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bulletprooflist
email: info@edmdesigner.com
description: > # this means to ignore newlines until "baseurl:"
  With Bulletprooflist you can easily generate the bulletrproof email version of an HTML list.
baseurl: "https://edmdesigner.github.io/bulletprooflist" # the subpath of your site, e.g. /blog

url: "https://edmdesigner.github.io/bulletprooflist/" # the base hostname & protocol for your site
demo: "https://edmdesigner.github.io/bulletprooflist/"
gaCode: UA-42954042-11
facebook_username: edmdesigner
twitter_username: EDMdesigner
github_username: EDMdesigner
linkedin_username: company/edmdesigner-com
google_username: +Edmdesigner
projectname: bulletprooflist 

# Build settings
markdown: kramdown
